title: DisMech
description: Open Source Codebase to simulate the dynamics of soft structures based on Discrete Differential Geometry methods
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/Radha-Lahoti/DER-Matlab-MultiRod
  team_url: /Contributors.html
